misc:
  exp_dir: kitti
  mode: train
  gpu_mode: True
  verbose: True
  verbose_freq: 200
  snapshot_freq: 1
  pretrain: ''


model:
  model: ResUNetBN2C
  in_feats_dim: 1
  out_feats_dim: 32
  conv1_kernel_size: 5
  normalize_feature: True
  dist_type: L2

overlap_attention_module:
  gnn_feats_dim: 256
  dgcnn_k: 10
  num_head: 4
  nets: ['self','cross','self']

loss:
  pos_margin: 0.1
  neg_margin: 1.4
  log_scale: 40
  pos_radius: 0.21
  safe_radius: 0.75
  overlap_radius: 0.45
  matchability_radius: 0.3 
  w_circle_loss: 1.0
  w_overlap_loss: 1.0
  w_saliency_loss: 0.0
  max_points: 512

optimiser:
  optimizer: SGD
  max_epoch: 200
  lr: 0.1
  momentum: 0.8
  weight_decay: 0.0001
  bn_momentum: 0.05
  scheduler: ExpLR
  scheduler_gamma: 0.99
  scheduler_freq: 1
  iter_size: 8

dataset:
  dataset: kitti
  benchmark: odometryKITTI
  root: /net/pf-pc27/scratch2/kitti
  voxel_size: 0.3
  batch_size: 1 
  num_workers: 6
  augment_noise: 0.01
  augment_shift_range: 2.0 
  augment_scale_max: 1.2
  augment_scale_min: 0.8

demo:
  src_pcd: assets/cloud_bin_21.pth
  tgt_pcd: assets/cloud_bin_34.pth
  n_points: 1000

